version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          name: login to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: check and initiate builds
          command: |
            pyenv global 3.5.2
            python3 -m venv venv
            . venv/bin/activate
            pip install -r docker/requirements.txt
            cd docker
            ./ansible_docker_build.py -o slim -l
            ./ansible_docker_build.py -o alpine

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build