version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run: ls -la 
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: build docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker/build-circleci.sh


workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^circleci$/