version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
          name: login to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - run:
          name: build docker slim images
          command: docker/build-circleci.sh -d slim -l
      
      - run:
          name: build docker alpine images
          command: docker/build-circleci.sh -d alpine


workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^circleci$/