version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: build docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            ls -la
            docker/build-circleci.sh