#!/bin/bash

. ../ANSIBLE_VERSION

DISTRO=$(echo $DOCKERFILE_PATH | sed -e 's/.*\/\(.*\)\/Dockerfile/\1/')

for version in $ANSIBLE_VERSION; do
    docker push ${DOCKER_REPO}:${version}-${DISTRO}
done
